services:
  - type: worker
    name: sbz1
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./data/sbz1.db
